### ISSUE TITLE
"Exception: Could not open window." on Mac

### ISSUE THREAD

**Issue by nhoma** [decisionforce/pgdrive#250]
Hello,

Thank you for pgdrive. I installed it on my macOS Big Sur with M1 chip using pip install. When running

```
python -m pgdrive.examples.enjoy_expert
```

I get the following error:

```
(pgdrive) ➜  ~ python -m pgdrive.examples.enjoy_expert
Successfully registered the following environments: ['PGDrive-test-v0', 'PGDrive-validation-v0', 'PGDrive-v0', 'PGDrive-10envs-v0', 'PGDrive-1000envs-v0', 'PGDrive-training0-v0', 'PGDrive-training1-v0', 'PGDrive-training2-v0'].
Known pipe types:
  CocoaGraphicsPipe
(all display modules loaded.)
:display:cocoadisplay(error): Could not find a usable pixel format.
:ShowBase(warning): Unable to open 'onscreen' window.
Traceback (most recent call last):
  File "/Users/namdar/opt/miniconda3/envs/pgdrive/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/namdar/opt/miniconda3/envs/pgdrive/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/namdar/opt/miniconda3/envs/pgdrive/lib/python3.9/site-packages/pgdrive/examples/enjoy_expert.py", line 15, in <module>
    obs = env.reset()
  File "/Users/namdar/opt/miniconda3/envs/pgdrive/lib/python3.9/site-packages/pgdrive/envs/pgdrive_env.py", line 250, in reset
    self.lazy_init()  # it only works the first time when reset() is called to avoid the error when render
  File "/Users/namdar/opt/miniconda3/envs/pgdrive/lib/python3.9/site-packages/pgdrive/envs/pgdrive_env.py", line 149, in lazy_init
    self.pg_world = PGWorld(self.pg_world_config)
  File "/Users/namdar/opt/miniconda3/envs/pgdrive/lib/python3.9/site-packages/pgdrive/world/pg_world.py", line 104, in __init__
    super(PGWorld, self).__init__(windowType=self.mode)
  File "/Users/namdar/opt/miniconda3/envs/pgdrive/lib/python3.9/site-packages/direct/showbase/ShowBase.py", line 339, in __init__
    self.openDefaultWindow(startDirect = False, props=props)
  File "/Users/namdar/opt/miniconda3/envs/pgdrive/lib/python3.9/site-packages/direct/showbase/ShowBase.py", line 1021, in openDefaultWindow
    self.openMainWindow(*args, **kw)
  File "/Users/namdar/opt/miniconda3/envs/pgdrive/lib/python3.9/site-packages/direct/showbase/ShowBase.py", line 1056, in openMainWindow
    self.openWindow(*args, **kw)
  File "/Users/namdar/opt/miniconda3/envs/pgdrive/lib/python3.9/site-packages/direct/showbase/ShowBase.py", line 801, in openWindow
    raise Exception('Could not open window.')
Exception: Could not open window.
(pgdrive) ➜  ~ python -m pgdrive.examples.enjoy_expert
```
 
Any idea on how to fix this? 

Thank you

**Comment by lqy0057** [comment]
Hi nhoma, this is an internal error of the game engine. I will ask for Panda3d official support. I will contact you as soon as possible if any progress.

**Comment by lqy0057** [comment]
Hi, you can track the progress of this [issue](https://discourse.panda3d.org/t/could-not-open-window-on-macos-mojave/24449/9). It seems that the game engine loses control of the new MacBook render pipeline. I will also synchronize the progress here to record the solution for other MacBook users.

**Comment by nhoma** [comment]
Thank you.

**Comment by pengzhenghao** [comment]
@lqy0057 Any update on this issue?
