### ISSUE TITLE
OSError: Could not load model file(s)

### ISSUE THREAD

**Issue by smitsavaliya-1258** [decisionforce/pgdrive#464]
my pc name is smits
i run this command
c:\Users\smits\pgdrive>python -m pgdrive.examples.enjoy_expert

Successfully registered the following environments: ['PGDrive-test-v0', 'PGDrive-validation-v0', 'PGDrive-v0', 'PGDrive-10envs-v0', 'PGDrive-1000envs-v0', 'PGDrive-training0-v0', 'PGDrive-training1-v0', 'PGDrive-training2-v0'].
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
WARNING:root:Since your screen is too small (1366, 768), we resize the window to (921, 691).
Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\lib\site-packages\gltf\converter.py", line 1918, in load_model
    convert(file_path, bamfilepath, gltf_settings)
  File "F:\ProgramData\Anaconda3\lib\site-packages\gltf\converter.py", line 1895, in convert
    gltf_data = json.load(gltf_file)
  File "F:\ProgramData\Anaconda3\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "F:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 49100: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\lib\site-packages\gltf\loader.py", line 17, in load_file
    return load_model(
  File "F:\ProgramData\Anaconda3\lib\site-packages\gltf\converter.py", line 1924, in load_model
    raise RuntimeError("Failed to convert glTF file")
RuntimeError: Failed to convert glTF file
:loader(error): Loading scene.gltf failed with RuntimeError exception.
:loader(error): Couldn't load file /c/Users/smits/pgdrive/pgdrive/assets/models/new/130/scene.gltf: invalid.
Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\smits\pgdrive\pgdrive\examples\enjoy_expert.py", line 15, in <module>
    obs = env.reset()
  File "c:\Users\smits\pgdrive\pgdrive\envs\base_env.py", line 313, in reset
    self.scene_manager.reset(
  File "c:\Users\smits\pgdrive\pgdrive\scene_manager\scene_manager.py", line 81, in reset
    self.traffic_manager.generate(pg_world=pg_world, map=self.map, traffic_density=traffic_density)
  File "c:\Users\smits\pgdrive\pgdrive\scene_manager\traffic_manager.py", line 91, in generate
    self._create_vehicles_once(pg_world, map, traffic_density)
  File "c:\Users\smits\pgdrive\pgdrive\scene_manager\traffic_manager.py", line 322, in _create_vehicles_once
    vehicles_on_block += self._create_vehicles_on_lane(traffic_density, l, False)
  File "c:\Users\smits\pgdrive\pgdrive\scene_manager\traffic_manager.py", line 286, in _create_vehicles_on_lane
    self.spawn_one_vehicle(vehicle_type, lane, long, is_respawn_lane)
  File "c:\Users\smits\pgdrive\pgdrive\scene_manager\traffic_manager.py", line 260, in spawn_one_vehicle
    random_v = vehicle_type.create_random_traffic_vehicle(
  File "c:\Users\smits\pgdrive\pgdrive\scene_creator\vehicle\traffic_vehicle.py", line 172, in create_random_traffic_vehicle
    return cls(index, v, enable_respawn, np_random=v.np_random)
  File "c:\Users\smits\pgdrive\pgdrive\scene_creator\vehicle\traffic_vehicle.py", line 70, in __init__
    carNP = self.loader.loadModel(AssetLoader.file_path("models", path))
  File "F:\ProgramData\Anaconda3\lib\site-packages\direct\showbase\Loader.py", line 298, in loadModel
    raise IOError(message)
OSError: Could not load model file(s): ['/c/Users/smits/pgdrive/pgdrive/assets/models/new/130/scene.gltf']

but got some errors

**Comment by lqy0057** [comment]
Hi, Smitsavaliya.
Thanks for your feedback. Actually, In Issue #251, Edward has reported this issue. The open() function in the third-party lib takes system encoding as default. If your system default encoding is not `utf-8`, this error will be raised. 

You can activate your environment and get the default encoding of python by `sys.getdefaultencoding()`.
If the result is not `utf-8`, you can try these ways:
- Set the environment variable to UTF-8, by set PYTHONIOENCODING=utf-8 in your terminal.
- Change the default encoding of windows
![image](https://user-images.githubusercontent.com/24489294/124854117-8a880780-dfd9-11eb-9d12-7bd15dfaf447.png)

However, If the return result is `utf-8`, there are other possible reasons. We find this error occurs when loading vehicle model130. Could you please change the source code in pgdrive/scene_creator/vehicle/traffic_vehicle_type.py from
```
class MVehicle(PGTrafficVehicle):
    LENGTH = 3.9
    WIDTH = 2.0
    HEIGHT = 1.3
    path = [
        ['new/130/scene.gltf', (factor * .0055, factor * .0046, factor * .0049), (0, 0, factor * 0.33), 90],
    ]
```
to
```
class MVehicle(PGTrafficVehicle):
    LENGTH = 3.2
    WIDTH = 1.8
    HEIGHT = 1.5
    path = [
        ['new/beetle/scene.gltf', (factor * .008, factor * .006, factor * .0062), (-0.7, 0, factor * -0.16), -90],
    ]
```
And then rerun `python -m pgdrive.examples.enjoy_expert`.  This will load vehicle beetle as M size vehicle, which can help determine if the model130 is broken.

**Comment by pengzhenghao** [comment]
@lqy0057 

Do we have any measure natively in PGDrive to solve this for all users?

**Comment by smitsavaliya-1258** [comment]
Hey,
It works by changing in source code as my environment is utf-8.

Thank you
